sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrumogic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexandrumogic/react-test npm test -- --coverage

after_success:
  - docker build -t alexandrumogic/multi-client ./client
  - docker build -t alexandrumogic/multi-nginx ./nginx
  - docker build -t alexandrumogic/multi-server ./server
  - docker build -t alexandrumogic/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push alexandrumogic/multi-client
  - docker push alexandrumogic/multi-nginx
  - docker push alexandrumogic/multi-server
  - docker push alexandrumogic/multi-worker
